[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tdd_roman_numeral_calculator"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath="src tests"
